# Generated by Django 2.2.5 on 2019-09-19 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20190919_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 9, 19, 17, 58, 55, 480601, tzinfo=utc))),
                ('task_type', models.CharField(choices=[('CALL', 'call'), ('EMAIL', 'email'), ('TEXT', 'text')], default='CALL', max_length=2)),
                ('follow_up_date', models.DateField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='follow_up_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 17, 58, 55, 480079, tzinfo=utc)),
        ),
    ]
