# Generated by Django 2.2.5 on 2019-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20190919_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='where',
            field=models.CharField(choices=[('SOCIAL', 'social media'), ('NEWS', 'newspaper'), ('GOOGLE', 'google'), ('FRIENDS', 'friends')], default='SOCIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(choices=[('OIL/GAS', 'oil/gas'), ('FARMING', 'farming'), ('CONSTRUCTION', 'construction')], default='OIL/GAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('CALL', 'call'), ('EMAIL', 'email'), ('TEXT', 'text')], default='CALL', max_length=50),
        ),
    ]
