# Generated by Django 2.2.5 on 2019-09-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_auto_20190919_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
